WebApp/Controllers/PagoController.cs
using LogicaDeAplicacion.DTOs;
using LogicaDeAplicacion.InterfacesCU.Pago;
using LogicaDeAplicacion.InterfacesCU.TipoDeGasto;
using LogicaDeNegocio.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;

namespace WebApp.Controllers
{
    [LogueadoFilter]
    public class PagoController : Controller
    {
        private IAgregarPago _agregarPago;
        private IObtenerPagos _obtenerPagos;
        private IObtenerPagosDadoAnioYmes _listarPagosMensuales;

        public PagoController(
               IAgregarPago agregarPago, 
               IObtenerPagos obtenerPagos,                             
               IObtenerPagosDadoAnioYmes listarPagosMensuales
               )
        {
                _agregarPago = agregarPago;
                _obtenerPagos = obtenerPagos;
                _listarPagosMensuales = listarPagosMensuales;
        }

        [NoDisponibleFilter]
        public ActionResult Index()
        {
            
            return View(_obtenerPagos.ObtenerPagos());
        }

    
        public ActionResult Details(int id)
        {
            return View();
        }

       
        public IActionResult Create(string error)
        {
            ViewBag.Error = error;
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PagoDTO pagoDTO)
        {
            try
            {
                int usuarioId = HttpContext.Session.GetInt32("usuarioId").Value;
                _agregarPago.AltaPago(pagoDTO, usuarioId);
                ViewBag.Mensaje = "Pago Registrado con exito";
                return View();
            }
            catch(PagoException pe)
            {
                ViewBag.Error = pe.Message;
                return View();
            }catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        
        public ActionResult Edit(int id)
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

      
        public ActionResult Delete(int id)
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [GerenteFilter]
        public IActionResult ListarPagosMensuales()
        {
            return View();
        }
        [GerenteFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ListarPagosMensuales(int mes, int anio)
        {
            var pagos = _listarPagosMensuales.ObtenerPagosPorMesYAño(mes, anio);

            if (!pagos.Any())
                ViewBag.Mensaje = "No existen pagos registrados en ese período.";

            return View(pagos);
        }

    }
}

WebApp/Controllers/TipoDeGastoController.cs
using LogicaDeAplicacion.CasosDeUso.TipoDeGasto;
using LogicaDeAplicacion.DTOs;
using LogicaDeAplicacion.InterfacesCU.TipoDeGasto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;

namespace WebApp.Controllers
{
    
    [LogueadoFilter]
    [AdminFilter]
    public class TipoDeGastoController : Controller
    {

        private IObtenerTipoDeGasto _obtenerTiposDeGasto;
        private IAgregarTipoDeGasto _agregarTipoDeGasto;
        private IEliminarTipoDeGasto _eliminarTipoDeGasto;
        private IObtenerTipoDeGastoPorId _obtenerTipoDeGastoPorId;
        private IEditarTipoDeGasto _editarTipoDeGasto;

        public TipoDeGastoController(
                    IObtenerTipoDeGasto obtenerTipoDeGasto,
                    IAgregarTipoDeGasto agregarTipoDeGasto,
                    IEliminarTipoDeGasto eliminarTipoDeGasto,
                    IObtenerTipoDeGastoPorId obtenerTipoDeGastoPorId,
                    IEditarTipoDeGasto editarTipoDeGasto)
        {
            _obtenerTiposDeGasto = obtenerTipoDeGasto;
            _agregarTipoDeGasto = agregarTipoDeGasto;
            _eliminarTipoDeGasto = eliminarTipoDeGasto;
            _obtenerTipoDeGastoPorId = obtenerTipoDeGastoPorId;
            _editarTipoDeGasto = editarTipoDeGasto;

        }

        public ActionResult Index()
        {
            
            return View(_obtenerTiposDeGasto.ObtenerTipoDeGasto());
        }

        public ActionResult Details(int id)
        {
            try
            {
               return View(_obtenerTipoDeGastoPorId.ObtenerTipoDeGastoPorId(id));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }            
        }

        public ActionResult Create()
        {
            
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoDeGastoDTO tipoDeGasto)
        {
            try
            {
                int usuarioId = HttpContext.Session.GetInt32("usuarioId").Value;
                _agregarTipoDeGasto.AgregarTipoDeGasto(tipoDeGasto, usuarioId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_obtenerTipoDeGastoPorId.ObtenerTipoDeGastoPorId(id));
            }
            catch (Exception)
            {
                ViewBag.Error = "Sucedio un error inesperado";
                return RedirectToAction(nameof(Index));
            }
            
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TipoDeGastoDTO tipoDTO)
        {
            try
            {
                int usuarioId = HttpContext.Session.GetInt32("usuarioId").Value;
                _editarTipoDeGasto.EditarTipoDeGasto(tipoDTO, usuarioId);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                ViewBag.Error = "Sucedio un error inesperado";
                return RedirectToAction(nameof(Index));
                
            }
        }

        
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_obtenerTipoDeGastoPorId.ObtenerTipoDeGastoPorId(id));
            }
            catch (Exception)
            {
                ViewBag.Error = "Sucedio un error inesperado";
                return RedirectToAction(nameof(Index));
               
            }
            
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                int usuarioId = HttpContext.Session.GetInt32("usuarioId").Value;
                _eliminarTipoDeGasto.EliminarTipoDeGasto(id, usuarioId);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                ViewBag.Error = "Sucedio un error inesperado";
                return View();

            }
        }
    }
}

WebApp/Controllers/UsuarioController.cs
using LogicaDeAplicacion.DTOs;
using LogicaDeAplicacion.InterfacesCU.Equipo;
using LogicaDeAplicacion.InterfacesCU.Usuario;
using LogicaDeNegocio.Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.Filters;


namespace WebApp.Controllers;

[LogueadoFilter]
public class UsuarioController : Controller
{
    
    private IAltaUsuario _altaUsuario;
    private IObtenerEquipos _obtenerEquipos;
    private IObtenerUsuariosSegunMonto _obtenerUsuarioSegunMonto;

    public UsuarioController(
        IAltaUsuario altaUsuario,
        IObtenerEquipos obtenerEquipos,
        IObtenerUsuariosSegunMonto obtenerUsuarioSegunMonto)
    {
        _altaUsuario = altaUsuario;
        _obtenerEquipos = obtenerEquipos;
        _obtenerUsuarioSegunMonto = obtenerUsuarioSegunMonto;
    }

 
    public IActionResult Index(string error)
    {
        ViewBag.Error = error;
        return View();
 
    }
    
    
    
    [AdminYGerenteFilter]
    public IActionResult Create()
    {
        try
        {
            IEnumerable<EquipoDTO> equipos = _obtenerEquipos.ObtenerEquipos();
            ViewBag.Equipos = new SelectList(equipos, "Id", "Nombre");
            return View();
        }
        catch (Exception)
        {
            return View();
        }
        
    }

    [AdminYGerenteFilter]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(UsuarioDTO usuarioDTO)
    {
        try
        {
            //int usuarioId = HttpContext.Session.GetInt32("usuarioId").Value;
            _altaUsuario.AgregarUsuario(usuarioDTO);
            return RedirectToAction("Index", "Home");
        }
        catch (Exception)
        {
            ViewBag.Error = "Ocurrio un error inesperado";
            return View();
        }
    }

    [GerenteFilter]
    public IActionResult UsuariosQueSuperanPagoDado()
    {
        return View();
    }

    [GerenteFilter]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult UsuariosQueSuperanPagoDado(decimal monto)
    {
        try
        {
            var usuarios = _obtenerUsuarioSegunMonto.ObtenerUsuariosSegunMonto(monto);
            return View(usuarios);
        }
        catch (Exception)
        {

            ViewBag.Error = "Ocurrio un error al filtrar los datos";
            return View();
        }
        
    }
   
}   

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAsspp</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="container navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">🏠 Inicio</a>
                        </li>
                        @if (Context.Session.GetInt32("usuarioId") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">🔐 Iniciar Sesión</a>
                            </li>
                        }
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoDeGasto" asp-action="Index">🧾 Tipos de Gasto </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Create">👤 Alta de Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="Create">💸 Registrar Pago</a>
                        </li>
            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="ListarPagosMensuales">📅 Listado Mensual de Pagos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="UsuariosQueSuperanPagoDado">💰 Usuarios que superan monto</a>
                        </li>
                        @if (Context.Session.GetInt32("usuarioId") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">🚪 Cerrar Sesión</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApp
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>